version: '3.4'

services:
  envvariabletest:
    image: envvariabletest
    build:
      context: .
      dockerfile: src/EnvVariableTest/Dockerfile
    environment: 
      - Host=${RabbitMQ_HOSTNAME}
      
      